# Generated by Django 3.2.10 on 2021-12-13 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_domain', '0001_initial'),
        ('user_domain', '0001_initial'),
        ('label_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='user_domain.workspace')),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'db_table': 'person_domain_person',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('info', models.JSONField(default=dict, help_text="Profile's info")),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='person_domain.person')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'db_table': 'person_domain_profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_profile', to='label_domain.label')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_label', to='person_domain.profile')),
            ],
            options={
                'unique_together': {('profile', 'label')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_groups',
            field=models.ManyToManyField(related_name='profiles', through='person_domain.ProfileGroup', to='label_domain.Label'),
        ),
        migrations.AddField(
            model_name='profile',
            name='samples',
            field=models.ManyToManyField(blank=True, related_name='profile', to='data_domain.Sample'),
        ),
        migrations.AddField(
            model_name='profile',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user_domain.workspace'),
        ),
    ]
