# Generated by Django 3.2.15 on 2022-09-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_domain', '0003_alter_blobmeta_blob'),
        ('person_domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='info',
            field=models.JSONField(default=dict, help_text="Person's info"),
        ),
        migrations.AddField(
            model_name='person',
            name='samples',
            field=models.ManyToManyField(blank=True, related_name='persons', to='data_domain.Sample'),
        ),
    ]
