# Generated by Django 3.2.18 on 2023-03-29 09:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_domain', '0004_profile_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesettings',
            name='extra_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
    ]
