# Generated by Django 3.2.9 on 2021-12-08 10:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('LO', 'Location'), ('PG', 'Profile Group'), ('AT', 'Area Type')], max_length=2)),
                ('title', models.CharField(max_length=500)),
                ('info', models.JSONField(default=dict)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='user_domain.workspace')),
            ],
            options={
                'verbose_name_plural': 'Labels',
                'db_table': 'label_domain_label',
            },
        ),
    ]
