# Generated by Django 3.2.13 on 2022-05-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_domain', '0002_transform_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='type',
            field=models.CharField(choices=[('WI', 'Web interface'), ('EM', 'Email'), ('WH', 'Webhook'), ('BT', 'Bot')], max_length=2),
        ),
    ]
