# Generated by Django 3.2.13 on 2022-06-02 11:57

from django.db import migrations

from notification_domain.managers import EndpointManager

endpoints = []


def create_default_endpoints(apps, schema_editor):
    workspace_model = apps.get_model('user_domain', 'Workspace')

    workspaces = workspace_model.objects.filter(endpoints__isnull=True)

    for workspace in workspaces:
        if (access := workspace.accesses.filter(permissions="AD").first()) is not None:
            user_email = access.user.username
            endpoints.append(EndpointManager(workspace_id=workspace.id).create_default_endpoints(user_email))


def rollback(apps, schema_editor):
    workspace_model = apps.get_model('user_domain', 'Workspace')

    workspaces = workspace_model.objects.filter(endpoints__isnull=False)

    for workspace in workspaces:
        workspace.endpoints.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notification_domain', '0003_alter_endpoint_type'),
    ]

    operations = [
        migrations.RunPython(create_default_endpoints, rollback)
    ]
