# Generated by Django 3.2.13 on 2022-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_domain', '0004_create_default_endpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
