# Generated by Django 3.2.15 on 2022-08-08 09:06

from django.db import migrations, models


def set_title(apps, schema_editor):
    Trigger = apps.get_model('notification_domain', 'Trigger')
    Label = apps.get_model('label_domain', 'Label')
    '''
    Trigger.meta['condition_language'] example:
    {
        'variables': {
            '0_v': {
                'type': 'presence',
                'target': [{'type': 'Label', 'uuid': '%UUID%'}, ...],
                ...
            }
        }
    }'''

    for trigger in Trigger.objects.all():
        items = trigger.meta.get('condition_language', {}).get('variables', {}).values()
        if not items:
            continue
        targets = []
        for item in items:
            targets += [target.get('uuid') for target in item.get('target') if target.get('type') == 'Label']
        label_titles = Label.objects.filter(id__in=targets).values_list('title', flat=True)
        trigger.title = f'Trigger for watchlist {",".join(label_titles)}'
        trigger.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notification_domain', '0005_auto_20220615_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.RunPython(set_title, reverse_code=migrations.RunPython.noop),
    ]
