# Generated by Django 3.2.10 on 2021-12-13 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_domain', '0001_initial'),
        ('collector_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.BinaryField(null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blobs',
                'db_table': 'data_domain_blob',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('meta', models.JSONField(default=dict, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='user_domain.workspace')),
            ],
            options={
                'verbose_name_plural': 'Samples',
                'db_table': 'data_domain_sample',
            },
        ),
        migrations.CreateModel(
            name='BlobMeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('meta', models.JSONField(default=dict, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('blob', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='data_domain.blob')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blobmeta', to='user_domain.workspace')),
            ],
            options={
                'verbose_name_plural': 'BlobMeta',
                'db_table': 'data_domain_blobmeta',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField(default=dict, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='collector_domain.camera')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'data_domain_activity',
            },
        ),
    ]
