# Generated by Django 3.2.10 on 2021-12-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person_domain', '0001_initial'),
        ('user_domain', '0001_initial'),
        ('data_domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='person_domain.person'),
        ),
        migrations.AddField(
            model_name='activity',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='user_domain.workspace'),
        ),
    ]
