# Generated by Django 3.2.15 on 2022-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_domain', '0003_alter_blobmeta_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Progress'), (2, 'Finalized'), (3, 'Failed')], default=1),
        ),
    ]
