# Generated by Django 3.2.15 on 2022-11-28 11:44

from django.db import migrations


def finalize_activities(apps, schema_editor):
    Activity = apps.get_model('data_domain', 'Activity')
    activities = Activity.objects.all()
    activities.update(status=2)  # FINALIZED type


def rollback(apps, schema_editor):
    # previous migration deletes field
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('data_domain', '0004_activity_status'),
    ]

    operations = [
        migrations.RunPython(finalize_activities, rollback),
    ]
