# Generated by Django 3.2.9 on 2021-12-06 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', help_text='Workspace tittle', max_length=100)),
                ('config', models.JSONField(db_index=True, default=dict, help_text='Workspace configuration. Include types of workspace')),
            ],
            options={
                'verbose_name_plural': 'Workspaces',
                'db_table': 'user_domain_workspace',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('permissions', models.CharField(choices=[('AD', 'Administrator'), ('VI', 'Viewer'), ('ED', 'Editor')], default='VI', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='user_domain.workspace')),
            ],
            options={
                'verbose_name_plural': 'Accesses',
                'db_table': 'user_domain_access',
            },
        ),
    ]
