# Generated by Django 3.2.12 on 2022-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_domain', '0002_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='permissions',
            field=models.CharField(choices=[('AD', 'Administrator'), ('VI', 'Viewer'), ('ED', 'Editor'), ('OW', 'Owner')], default='VI', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='access',
            constraint=models.UniqueConstraint(condition=models.Q(('permissions', 'OW')), fields=('workspace', 'permissions'), name='unique owner'),
        ),
    ]
