# Generated by Django 3.2.14 on 2022-08-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_domain', '0003_auto_20220323_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='title',
            field=models.CharField(default='', help_text='Workspace title', max_length=100),
        ),
    ]
