# Generated by Django 3.2.13 on 2022-08-05 09:52

import logging
from django.db import migrations
from django.conf import settings

from user_domain.models import Workspace

logger = logging.getLogger(__name__)


def _update_config(workspace: Workspace) -> bool:
    try:
        workspace.config['sample_ttl'] = settings.SAMPLE_TTL
        workspace.save()
        return True
    except Exception as ex:
        logger.warning(f"Failed to update the workspace config: {str(workspace.id)}")
        return False


def _rollback_config(workspace: Workspace):
    try:
        workspace.config.pop('sample_ttl')
        workspace.save()
    except Exception as ex:
        logger.warning(f"Failed to rollback the workspace config: {str(workspace.id)}")


def add_sample_ttl(apps, schema_editor):
    """
    Add sample time to live in all workspace.
    Default time 30 days or 2592000 seconds.
    """
    logger.info(f"Add sample time to live ...")

    workspace_model = apps.get_model('user_domain', 'Workspace')
    quantity = 0  # total count of migrated workspaces
    skipped_workspaces = []  # workspaces that have not been migrated

    for ws in workspace_model.objects.all():
        if _update_config(ws):
            quantity += 1
        else:
            skipped_workspaces.append(str(ws.id))

    logger.info(f'Migration have been done. '
                f'Quantity of migrated workspaces: {quantity}/{workspace_model.objects.count()}')
    if skipped_workspaces:
        skipped_workspaces_string = '\n'.join(skipped_workspaces)
        logger.warning(f'Skipped workspaces due to broken config:\n{skipped_workspaces_string}\n')


def rollback(apps, schema_editor):
    logger.info(f"Rollback migration sample ttl in workspaces ...")

    workspace_model = apps.get_model('user_domain', 'Workspace')
    quantity = 0  # total count of migrated workspaces

    for ws in workspace_model.objects.all():
        if _rollback_config(ws):
            quantity += 1

    logger.info(f'Rollback have been done. '
                f'Quantity of rollback workspaces: {quantity}/{workspace_model.objects.count()}')


class Migration(migrations.Migration):

    dependencies = [
        ('user_domain', '0004_alter_workspace_title'),
    ]

    operations = [
        migrations.RunPython(add_sample_ttl, rollback)
    ]
