# Generated by Django 3.2.10 on 2021-12-13 13:32

import collector_domain.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_domain', '0001_initial'),
        ('label_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('info', models.JSONField(default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='user_domain.workspace')),
            ],
            options={
                'verbose_name': 'Agent',
                'db_table': 'collector_domain_agent',
            },
            bases=(models.Model, collector_domain.models.ModelMixin),
        ),
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='collector_domain.agent')),
            ],
            options={
                'verbose_name': 'Camera',
                'db_table': 'collector_domain_camera',
            },
            bases=(models.Model, collector_domain.models.ModelMixin),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_location', to='collector_domain.camera')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_location', to='label_domain.label')),
            ],
            options={
                'unique_together': {('camera', 'label')},
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='locations',
            field=models.ManyToManyField(related_name='cameras', through='collector_domain.Location', to='label_domain.Label'),
        ),
        migrations.AddField(
            model_name='camera',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='user_domain.workspace'),
        ),
        migrations.CreateModel(
            name='AttentionArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('info', models.JSONField(default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('area_types', models.ManyToManyField(related_name='attention_areas', through='collector_domain.AreaType', to='label_domain.Label')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_areas', to='collector_domain.camera')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_areas', to='user_domain.workspace')),
            ],
            options={
                'verbose_name': 'Attention area',
                'db_table': 'collector_domain_attention_area',
            },
        ),
        migrations.AddField(
            model_name='areatype',
            name='attention_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_type', to='collector_domain.attentionarea'),
        ),
        migrations.AddField(
            model_name='areatype',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_type', to='label_domain.label'),
        ),
        migrations.AlterUniqueTogether(
            name='areatype',
            unique_together={('attention_area', 'label')},
        ),
    ]
