# Generated by Django 3.2.15 on 2022-09-15 13:52

from django.db import migrations, models
import platform_lib.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collector_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentIndexEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=30)),
                ('workspace_id', models.UUIDField()),
                ('profile_id', models.UUIDField()),
                ('person_id', models.UUIDField()),
                ('data', models.JSONField(default=dict)),
                ('creation_date', models.DateTimeField(default=platform_lib.utils.utcnow_with_tz)),
            ],
        ),
        migrations.AddIndex(
            model_name='agentindexevent',
            index=models.Index(fields=['creation_date'], name='collector_d_creatio_8bd586_idx'),
        ),
    ]
