#  Generated by Django 3.2.16 on 2022-11-25 06:01

import django.contrib.postgres.fields
from django.db import migrations, models, transaction
import uuid
from main.settings import REQUIRED_CAMERA_FIELDS


def forward(apps, schema_editor):
    Workspace = apps.get_model('user_domain', 'Workspace')
    Camera = apps.get_model('collector_domain', 'Camera')
    CollectorSettings = apps.get_model('collector_domain', 'CollectorSettings')
    with transaction.atomic():
        for ws in Workspace.objects.all():
            CollectorSettings.objects.create(workspace_id=ws.id, camera_fields=REQUIRED_CAMERA_FIELDS)

        for cam in Camera.objects.select_for_update().all():
            cam.info = {'title': cam.title}
            cam.save()


def rollback(apps, schema_editor):
    Camera = apps.get_model('collector_domain', 'Camera')
    with transaction.atomic():
        for cam in Camera.objects.select_for_update().all():
            cam.title = cam.info.get('title', getattr(cam.agent,'title', ''))
            cam.save()


class Migration(migrations.Migration):

    dependencies = [
        ('collector_domain', '0002_auto_20220915_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('workspace_id', models.UUIDField(editable=False)),
                ('camera_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'CollectorSettings',
                'db_table': 'collector_settings',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='info',
            field=models.JSONField(default=dict, help_text="Profile's info"),
        ),
        migrations.RunPython(forward, rollback),
        migrations.RemoveField(
            model_name='camera',
            name='title',
        ),
    ]
