# Generated by Django 3.2.16 on 2022-12-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector_domain', '0003_auto_20221125_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='collector_domain.agent'),
        ),
    ]
