# Generated by Django 3.2.18 on 2023-03-29 09:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector_domain', '0004_alter_camera_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='collector_domain.agent'),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='camera_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None),
        ),
    ]
