# Generated by Django 3.2.10 on 2021-12-22 09:45

from django.db import migrations, models
import django.db.models.deletion
import platform_lib.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collector_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('signature', models.JSONField(default=dict)),
                ('creation_date', models.DateTimeField(default=platform_lib.utils.utcnow_with_tz)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activations', to='collector_domain.agent')),
                ('previous_activation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_activation', to='activation_manager.activation')),
            ],
            options={
                'db_table': 'agent_activation',
            },
        ),
    ]
