# Generated by Django 3.2.14 on 2022-08-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector_domain', '0001_initial'),
        ('activation_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='collector_domain.agent'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='previous_activation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_activation', to='activation_manager.activation'),
        ),
    ]
