# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"#\n\x13\x41ntispoofingRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x0c\":\n\x14\x41ntispoofingResponse\x12\x0e\n\x06isReal\x18\x01 \x01(\x08\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32\x46\n\x0c\x41ntispoofing\x12\x36\n\x07\x45xecute\x12\x14.AntispoofingRequest\x1a\x15.AntispoofingResponseB\x16\xaa\x02\x13\x41ntispoofing.protosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\023Antispoofing.protos'
  _ANTISPOOFINGREQUEST._serialized_start=17
  _ANTISPOOFINGREQUEST._serialized_end=52
  _ANTISPOOFINGRESPONSE._serialized_start=54
  _ANTISPOOFINGRESPONSE._serialized_end=112
  _ANTISPOOFING._serialized_start=114
  _ANTISPOOFING._serialized_end=184
# @@protoc_insertion_point(module_scope)
