# Generated by Django 3.2.13 on 2022-05-25 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_domain', '0003_auto_20220323_0936'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'BillingAccounts',
                'db_table': 'licensing_billing_account',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('config', models.JSONField(default=dict)),
                ('expiration_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Licenses',
                'db_table': 'licensing_license',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'licensing_product',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(max_length=64)),
                ('request_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'WebhookLogs',
                'db_table': 'licensing_webhook_log',
            },
        ),
        migrations.AddConstraint(
            model_name='webhooklog',
            constraint=models.UniqueConstraint(fields=('source', 'request_id'), name='unique_request_per_source'),
        ),
        migrations.AddField(
            model_name='license',
            name='billing_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licensing.billingaccount'),
        ),
        migrations.AddField(
            model_name='license',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='licensing.product'),
        ),
        migrations.AddField(
            model_name='license',
            name='workspace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_domain.workspace'),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AutonomousLicense',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('licensing.license',),
        ),
        migrations.CreateModel(
            name='WorkspaceLicense',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('licensing.license',),
        ),
    ]
